require:
  - rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/EmptyMethod:
  Enabled: false

AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/{bundle,rails,rake}"
    - "**/old_and_unused.rb"
